// Dados iniciais usados como fallback e seed para a primeira carga da loja.
window.PODEROSA_FALLBACK_PRODUCTS = [
  {
    id: 1,
    nome: "Conjunto Branco B Body",
    slug: "conjunto-branco-b-body",
    descricao: "Conjunto fitness premium com tecido tecnologico, compressao confortavel e acabamento sofisticado.",
    preco: 259.9,
    preco_promocional: null,
    categoria: "Conjuntos",
    tamanhos: ["P", "M", "G"],
    cores: ["rosa", "preto"],
    imagens: ["assets/conjunto-capa/2.jpg", "assets/conjunto-capa/3.jpg", "assets/conjunto-capa/4.jpg", "assets/conjunto-capa/5.jpg", "assets/conjunto-capa/6.jpg"],
    imagem_principal: "assets/conjunto-capa/2.jpg",
    status: "novo",
    estoque: null,
    em_destaque: true,
    no_banner: true,
    ativo: true,
    criado_em: "2026-01-10T10:00:00.000Z",
    atualizado_em: "2026-01-10T10:00:00.000Z"
  },
  {
    id: 2,
    nome: "Conjunto B Body Rose",
    slug: "conjunto-b-body-rose",
    descricao: "Top fitness com design moderno e tecido que respira.",
    preco: 129.9,
    preco_promocional: null,
    categoria: "Top",
    tamanhos: ["P", "M", "G", "GG"],
    cores: ["rosa", "preto", "cinza"],
    imagens: ["assets/top-power/conjuto 1.jpg", "assets/top-power/conjuto 1.2.jpg", "assets/top-power/conjuto 1.3.jpg", "assets/top-power/2.jpg"],
    imagem_principal: "assets/top-power/conjuto 1.jpg",
    status: "mais_vendido",
    estoque: null,
    em_destaque: true,
    no_banner: false,
    ativo: true,
    criado_em: "2026-01-12T10:00:00.000Z",
    atualizado_em: "2026-01-12T10:00:00.000Z"
  },
  {
    id: 3,
    nome: "Macaquinho Move",
    slug: "macaquinho-move",
    descricao: "Macaquinho fitness com modelagem perfeita para todos os tipos de treino.",
    preco: 199.9,
    preco_promocional: null,
    categoria: "Macaquinho",
    tamanhos: ["P", "M", "G"],
    cores: ["preto", "cinza"],
    imagens: ["assets/macaquinho-move/1 (2).jpg", "assets/macaquinho-move/2 (2).jpg"],
    imagem_principal: "assets/macaquinho-move/1 (2).jpg",
    status: "novo",
    estoque: null,
    em_destaque: false,
    no_banner: false,
    ativo: true,
    criado_em: "2026-01-14T10:00:00.000Z",
    atualizado_em: "2026-01-14T10:00:00.000Z"
  },
  {
    id: 4,
    nome: "Conjunto Strong",
    slug: "conjunto-strong",
    descricao: "Conjunto strong para alta performance nos treinos.",
    preco: 259.9,
    preco_promocional: 229.9,
    categoria: "Conjuntos",
    tamanhos: ["P", "M", "G", "GG"],
    cores: ["preto", "rosa", "azul"],
    imagens: ["assets/conjunto-strong/1 (1).jpg", "assets/conjunto-strong/2 (2).jpg"],
    imagem_principal: "assets/conjunto-strong/1 (1).jpg",
    status: "promocao",
    estoque: null,
    em_destaque: true,
    no_banner: false,
    ativo: true,
    criado_em: "2026-01-16T10:00:00.000Z",
    atualizado_em: "2026-01-16T10:00:00.000Z"
  },
  {
    id: 5,
    nome: "Short Run",
    slug: "short-run",
    descricao: "Short leve e confortavel para corrida e academia.",
    preco: 99.9,
    preco_promocional: null,
    categoria: "Short",
    tamanhos: ["P", "M", "G"],
    cores: ["preto", "cinza", "rosa"],
    imagens: ["assets/short-run/1 (2).jpg", "assets/short-run/3.jpg", "assets/short-run/4.jpg"],
    imagem_principal: "assets/short-run/1 (2).jpg",
    status: "mais_vendido",
    estoque: null,
    em_destaque: false,
    no_banner: false,
    ativo: true,
    criado_em: "2026-01-18T10:00:00.000Z",
    atualizado_em: "2026-01-18T10:00:00.000Z"
  },
  {
    id: 6,
    nome: "Legging Essential",
    slug: "legging-essential",
    descricao: "Legging essencial com alta compressao e conforto.",
    preco: 159.9,
    preco_promocional: null,
    categoria: "Legging",
    tamanhos: ["P", "M", "G", "GG"],
    cores: ["preto", "cinza", "azul"],
    imagens: ["assets/legging-essential/1 (2).jpg"],
    imagem_principal: "assets/legging-essential/1 (2).jpg",
    status: "novo",
    estoque: null,
    em_destaque: false,
    no_banner: false,
    ativo: true,
    criado_em: "2026-01-20T10:00:00.000Z",
    atualizado_em: "2026-01-20T10:00:00.000Z"
  },
  {
    id: 7,
    nome: "Top Cloud",
    slug: "top-cloud",
    descricao: "Top cloud com sensacao de leveza e suporte ideal.",
    preco: 119.9,
    preco_promocional: null,
    categoria: "Top",
    tamanhos: ["P", "M", "G"],
    cores: ["branco", "cinza", "rosa"],
    imagens: ["assets/top-cloud/1 (2).jpg", "assets/top-cloud/2 (2).jpg"],
    imagem_principal: "assets/top-cloud/1 (2).jpg",
    status: "novo",
    estoque: null,
    em_destaque: false,
    no_banner: false,
    ativo: true,
    criado_em: "2026-01-22T10:00:00.000Z",
    atualizado_em: "2026-01-22T10:00:00.000Z"
  },
  {
    id: 8,
    nome: "Top Cacao",
    slug: "top-cacao",
    descricao: "Top cacao com tecido macio e modelagem perfeita.",
    preco: 139.9,
    preco_promocional: null,
    categoria: "Top",
    tamanhos: ["P", "M", "G", "GG"],
    cores: ["marrom", "preto", "rosa"],
    imagens: ["assets/top-cacao/1.jpg", "assets/top-cacao/2.jpg"],
    imagem_principal: "assets/top-cacao/1.jpg",
    status: "mais_vendido",
    estoque: null,
    em_destaque: false,
    no_banner: false,
    ativo: true,
    criado_em: "2026-01-24T10:00:00.000Z",
    atualizado_em: "2026-01-24T10:00:00.000Z"
  },
  {
    id: 9,
    nome: "Top Cross Rose",
    slug: "top-cross-rose",
    descricao: "Top cross rose com design cruzado nas costas.",
    preco: 149.9,
    preco_promocional: null,
    categoria: "Top",
    tamanhos: ["P", "M", "G"],
    cores: ["rosa", "preto"],
    imagens: ["assets/top-cross-rose/1 (2).jpg", "assets/top-cross-rose/2 (2).jpg"],
    imagem_principal: "assets/top-cross-rose/1 (2).jpg",
    status: "novo",
    estoque: null,
    em_destaque: false,
    no_banner: false,
    ativo: true,
    criado_em: "2026-01-26T10:00:00.000Z",
    atualizado_em: "2026-01-26T10:00:00.000Z"
  },
  {
    id: 10,
    nome: "Top Olive",
    slug: "top-olive",
    descricao: "Top olive com modelagem diferenciada.",
    preco: 129.9,
    preco_promocional: null,
    categoria: "Top",
    tamanhos: ["P", "M", "G"],
    cores: ["verde", "preto", "cinza"],
    imagens: ["assets/top-olive/1.jpg", "assets/top-olive/2.jpg"],
    imagem_principal: "assets/top-olive/1.jpg",
    status: "novo",
    estoque: null,
    em_destaque: false,
    no_banner: false,
    ativo: true,
    criado_em: "2026-01-28T10:00:00.000Z",
    atualizado_em: "2026-01-28T10:00:00.000Z"
  },
  {
    id: 11,
    nome: "Conjunto Aurora",
    slug: "conjunto-aurora",
    descricao: "Conjunto aurora com estampa exclusiva e tecido premium.",
    preco: 289.9,
    preco_promocional: null,
    categoria: "Conjuntos",
    tamanhos: ["P", "M", "G", "GG"],
    cores: ["preto", "branco", "rosa"],
    imagens: ["assets/conjunto-aurora/1.jpg", "assets/conjunto-aurora/2.jpg"],
    imagem_principal: "assets/conjunto-aurora/1.jpg",
    status: "mais_vendido",
    estoque: null,
    em_destaque: true,
    no_banner: false,
    ativo: true,
    criado_em: "2026-01-30T10:00:00.000Z",
    atualizado_em: "2026-01-30T10:00:00.000Z"
  }
];

window.defaultProducts = window.PODEROSA_FALLBACK_PRODUCTS;
